name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-and-deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: release
      uses: manoadamro/rust-release@v1
      with:
    # Github Repo Owner
        owner: ${{ github.repository_owner }}
    # Github Repo
        repo: ${{ github.repository }}
    # Github Token
        token: ${{ secrets.GITHUB_TOKEN }}
    # Cargo.toml path
        cargo: Cargo.toml
    # do not actually create release
        dry_run: false
